app:
  new_flag_img: '![news](https://github.com/lyy289065406/lyy289065406/blob/master/imgs/new.gif)'
  activity_num: 8              # 展示的活动项数
  article_num: 9               # 展示的文章项数
  skip_repos:
    - '.*?demo.*'
    - 'crop-circles'
    - 'threat-broadcast'
    - 'steam-discount'
    - 'articles'
    - 'hexo-blog'
    - 'hexo-store'
    - 'ro-store'
    - 'music-library'
    - 'ebooks-library'
    - 're0-web'
    - 'idea-cloud-settings'
    - 'store-material'
    - 'vulhub'
    - 'node_modules'
    - 'exp-blog'
    
github:
  proxy: "<%= ENV['PROXY'] %>"  # 连接到 Github 的代理服务，如： http://127.0.0.1:8888, socks5://127.0.0.1:1088
  owner: 'lyy289065406'
  url: 'https://github.com'
  graphql: 'https://api.github.com/graphql'
  gtk: "<%= ENV['GTK'] %>"      # Github Token
